server:
  port: 8084

spring:
  application:
    name: ai-agent-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info