export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    user: '/users/me',
    userPassword: '/users/me/password',
    userPreferences: '/users/me/preferences',
    enableTwoFactor: '/users/me/2fa/enable',
  },
  dashboard: {
    metrics: '/dashboard/metrics',
    activity: '/dashboard/activity',
    health: '/health/services',
  },
  ai: {
    chat: '/ai/chat',
    chats: '/ai/chats',
    messages: (chatId: string) => `/ai/chats/${chatId}/messages`,
    attachments: (chatId: string) => `/ai/chats/${chatId}/attachments`,
  },
  emails: {
    list: '/emails',
    detail: (id: string) => `/emails/${id}`,
    ingest: '/emails/ingest',
    extractTasks: (id: string) => `/emails/${id}/extract-tasks`,
    stats: '/emails/stats',
  },
  tasks: {
    list: '/tasks',
    create: '/tasks',
    update: (id: string) => `/tasks/${id}`,
    remove: (id: string) => `/tasks/${id}`,
    board: '/tasks/board',
  },
  documents: {
    upload: '/documents/upload',
    list: '/documents',
    detail: (id: string) => `/documents/${id}`,
    ask: (id: string) => `/documents/${id}/ask`,
    chunks: (id: string) => `/documents/${id}/chunks`,
  },
  reports: {
    list: '/reports',
    generate: '/reports/generate',
    detail: (id: string) => `/reports/${id}`,
    analytics: '/reports/analytics',
  },
  notifications: {
    list: '/notifications',
    recent: '/notifications/recent',
    read: (id: string) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
    remove: (id: string) => `/notifications/${id}`,
  },
  workflows: {
    list: '/workflows',
    create: '/workflows',
    remove: (id: string) => `/workflows/${id}`,
    status: (id: string) => `/workflows/${id}/status`,
    run: (id: string) => `/workflows/${id}/run`,
    executions: (id: string) => `/workflows/${id}/executions`,
    events: '/workflows/events',
  },
  integrations: {
    list: '/integrations',
    connect: (provider: string) => `/integrations/${provider}/connect`,
    disconnect: (provider: string) => `/integrations/${provider}/disconnect`,
    webhook: (provider: string) => `/integrations/webhooks/${provider}`,
  },
} as const;
